#!/bin/bash

## Completions ##
eval "$(direnv hook bash)"
eval "$(docker completion bash)"
eval "$(helm completion bash)"
eval "$(helmfile completion bash)"
# eval "$(just --completions bash)"
eval "$(kubectl completion bash)"

## Core command aliases ##
alias d=docker
alias g=git
alias h=helm
alias hf=helmfile
alias k=kubectl

## Utility aliases ##
alias week="date +%V" # Get week number
alias reload='exec ${SHELL} -l' # Reload the shell (i.e. invoke as a login shell)

## Alias Completions ##
source /usr/share/bash-completion/completions/git
__git_complete g __git_main

complete -o default -F __start_docker d
complete -o default -F __start_helm h
complete -o default -F __start_helmfile hf
complete -o default -F __start_kubectl k
